# Generated by Django 5.0.4 on 2024-05-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
