# Generated by Django 5.0.4 on 2024-05-06 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0002_alter_persona_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipodocumento',
            new_name='td',
        ),
    ]
