# Generated by Django 5.0.4 on 2024-07-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0003_rename_tipodocumento_td'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='lugarresidencia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='idtipodocumento',
        ),
        migrations.AlterField(
            model_name='td',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
