# Generated by Django 5.0.4 on 2024-07-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0004_remove_persona_lugarresidencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipodocumento', models.CharField(verbose_name=100)),
                ('documento', models.IntegerField()),
                ('lugarResidencia', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('idciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodocumento.ciudad')),
                ('idtipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipodocumento.td')),
            ],
        ),
    ]
