# Generated by Django 5.0.4 on 2024-07-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0007_alter_persona_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='lugarResidencia',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipodocumento',
        ),
    ]
