# Generated by Django 5.0.4 on 2024-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0008_remove_persona_lugarresidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
