# Generated by Django 5.0.4 on 2024-07-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0009_persona_is_active_persona_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.BigIntegerField(),
        ),
    ]
