# Generated by Django 5.0.4 on 2024-07-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipodocumento', '0010_alter_persona_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='usuario',
            new_name='username',
        ),
    ]
